#!/usr/bin/env node
/**
 * Daily Memory Auto-Update
 * 
 * Automatically appends session summaries to memory/YYYY-MM-DD.md
 * Run via cron or heartbeat to maintain continuous context.
 * 
 * Task 1.3 of Agent Persistence Work Plan
 * Author: Cassian Sandman
 * Date: 2026-02-01
 */

const fs = require('fs');
const path = require('path');

const MEMORY_DIR = path.join(__dirname, '..', 'memory');
const ACTIVITY_STATE = path.join(__dirname, 'activity_state.json');

function getToday() {
  return new Date().toISOString().split('T')[0];
}

function getTodayFile() {
  return path.join(MEMORY_DIR, `${getToday()}.md`);
}

function ensureMemoryDir() {
  if (!fs.existsSync(MEMORY_DIR)) {
    fs.mkdirSync(MEMORY_DIR, { recursive: true });
  }
}

function getActivityState() {
  try {
    if (fs.existsSync(ACTIVITY_STATE)) {
      return JSON.parse(fs.readFileSync(ACTIVITY_STATE, 'utf8'));
    }
  } catch (e) {
    console.error('Error reading activity state:', e.message);
  }
  return { agents: {} };
}

function formatTimestamp() {
  return new Date().toISOString().replace('T', ' ').split('.')[0] + ' UTC';
}

function appendToMemory(content) {
  ensureMemoryDir();
  const file = getTodayFile();
  
  // Create file with header if it doesn't exist
  if (!fs.existsSync(file)) {
    const header = `# Daily Log — ${getToday()}\n\n*Auto-generated by daily_memory_update.js*\n\n---\n\n`;
    fs.writeFileSync(file, header);
  }
  
  fs.appendFileSync(file, content + '\n');
  return file;
}

function generateStatusEntry() {
  const state = getActivityState();
  const timestamp = formatTimestamp();
  
  let entry = `## ${timestamp} — Auto Status Update\n\n`;
  
  // Agent status
  entry += '### Agent Status\n';
  for (const [agent, data] of Object.entries(state.agents || {})) {
    const lastActive = data.lastActivity ? new Date(data.lastActivity).toISOString() : 'unknown';
    const status = data.status || 'unknown';
    entry += `- **${agent}:** ${status} (last: ${lastActive})\n`;
  }
  
  // Try to get queue status
  try {
    const queueFile = path.join(__dirname, 'task_queue.json');
    if (fs.existsSync(queueFile)) {
      const queue = JSON.parse(fs.readFileSync(queueFile, 'utf8'));
      entry += `\n### Queue Status\n`;
      entry += `- **Queued tasks:** ${queue.length}\n`;
      if (queue.length > 0) {
        entry += `- **Top priority:** ${queue[0].description} (${queue[0].priority_score} pts)\n`;
      }
    }
  } catch (e) {
    // Ignore queue errors
  }
  
  entry += '\n---\n';
  return entry;
}

function logEvent(eventType, details) {
  const timestamp = formatTimestamp();
  let entry = `## ${timestamp} — ${eventType}\n\n`;
  
  if (typeof details === 'object') {
    for (const [key, value] of Object.entries(details)) {
      entry += `- **${key}:** ${value}\n`;
    }
  } else {
    entry += details + '\n';
  }
  
  entry += '\n---\n';
  
  const file = appendToMemory(entry);
  console.log(`Logged ${eventType} to ${file}`);
  return { success: true, file, eventType };
}

function runStatusUpdate() {
  const entry = generateStatusEntry();
  const file = appendToMemory(entry);
  console.log(`Status update written to ${file}`);
  return { success: true, file };
}

// CLI interface
const args = process.argv.slice(2);
const command = args[0] || 'status';

switch (command) {
  case 'status':
    const result = runStatusUpdate();
    console.log(JSON.stringify(result, null, 2));
    break;
    
  case 'log':
    const eventType = args[1] || 'Note';
    const details = args[2] || 'Manual entry';
    const logResult = logEvent(eventType, details);
    console.log(JSON.stringify(logResult, null, 2));
    break;
    
  case 'init':
    ensureMemoryDir();
    const file = getTodayFile();
    if (!fs.existsSync(file)) {
      const header = `# Daily Log — ${getToday()}\n\n## Session Start\n\nNew day initialized.\n\n---\n`;
      fs.writeFileSync(file, header);
      console.log(`Created ${file}`);
    } else {
      console.log(`${file} already exists`);
    }
    break;
    
  default:
    console.log(`
Daily Memory Auto-Update

Usage:
  node daily_memory_update.js status    — Append status update to today's memory
  node daily_memory_update.js log TYPE "DETAILS"  — Log a specific event
  node daily_memory_update.js init      — Initialize today's memory file

Examples:
  node daily_memory_update.js log "Task Complete" "Fixed connector.py context field"
  node daily_memory_update.js status
`);
}
